export const chartThemeList = [
   { value: "defaultTheme", label: "Default Theme" },
   { value: "darkEarth", label: "Dark Earth" },
   { value: "lightEarth", label: "Light Earth" },
   { value: "lightBlue", label: "Light Blue" },
   { value: "darkBlue", label: "Dark Blue" },
   { value: "lightGlamour", label: "Light Glamour" },
   { value: "darkGlamour", label: "Dark Glamour" },
   { value: "lightProvence", label: "Light Provence" },
   { value: "darkProvence", label: "Dark Provence" },
   { value: "lightTurquoise", label: "Light Turquoise" },
   { value: "darkTurquoise", label: "Dark Turquoise"  },
   { value: "coffee", label: "Coffee", theme: "Coffee" },
   { value: "monochrome", label: "Monochrome"  },
   { value: "morning", label: "Morning"  },
   { value: "pastel", label: "Pastel"  },
   { value: "sea", label: "Sea" },
   { value: "wines", label: "Wines" },
];

export const annotationList = [
   { value: "default", label: "Annotation Type" },	
   { value: "andrews-pitchfork", label: "Andrews Pitchfork" },	
   { value: "ellipse	Ellipse", label: "Ellipse" },	
   { value: "fibonacci-arc", label: "Fibonacci arc" },	
   { value: "fibonacci-fan", label: "Fibonacci fan" },	
   { value: "fibonacci-retracement", label: "Fibonacci retracement" },	
   { value: "fibonacci-timezones", label: "Fibonacci timezones" },	
   { value: "horizontal-line", label: "Horizontal line" },	
   { value: "infinite-line", label: "Infinite line" },	
   { value: "label", label: "Label" },	
   { value: "line", label: "Line" },	
   { value: "marker", label: "Marker" },	
   { value: "ray", label: "Ray" },	
   { value: "rectangle", label: "Rectangle" },	
   { value: "trend-channel", label: "Trend channel" },	
   { value: "triangle", label: "Triangle" },	
   { value: "vertical-line", label: "Vertical line" },
];

export const seriesTypeList = [
   { value: "area", label: "Area Chart" },
   { value: "candlestick", label: "Candlestick Chart" },
   { value: "column", label: "Column Chart" },
   { value: "jumpLine", label: "Jump Line Chart" },
   { value: "line", label: "Line Chart" },
   { value: "marker", label: "Marker Chart" },
   { value: "ohlc", label: "OHLC Chart" },
   { value: "rangeArea", label: "Range Area Chart" },
   { value: "rangeColumn", label: "Range Column Chart" },
   { value: "rangeSplineArea", label: "Range Spline Area Chart" },
   { value: "rangeStepArea", label: "Range Step Area Chart" },
   { value: "spline", label: "Spline Chart" },
   { value: "splineArea", label: "Spline Area Chart" },
   { value: "stepArea", label: "Step Area Chart" },
   { value: "stepLine", label: "Step Line Chart" },
   { value: "stick", label: "Stick Chart" },
];

export const indicatorList = [
   { value: "ama", label: "Adaptive Moving Average (AMA)" },
   { value: "aroon", label: "Aroon" },
   { value: "atr", label: "Average True Range (ATR)" },
   { value: "ao", label: "Awesome Oscillator (AO)" },
   { value: "bbands", label: "Bollinger Bands (BBands)" },
   { value: "bbandsB", label: "Bollinger Bands %B (BBands B)" },
   { value: "bbandsWidth", label: "Bollinger Bands Width (BBands Width)" },
   { value: "ema", label: "Exponential moving average (EMA)" },
   { value: "ha", label: "Heikin-Ashi (HA)" },
   { value: "stochastic", label: "Stochastic Oscillator (Full)" },
   { value: "fastStochastic", label: "Stochastic Oscillator (Fast)" },
   { value: "slowStochastic", label: "Stochastic Oscillator (Slow)" },
   { value: "kdj", label: "KDJ" },
   { value: "keltnerChannels", label: "KeltnerChannels" },
   { value: "mma", label: "Modified Moving Average (MMA)" },
   { value: "macd", label: "Moving Average Convergence/Divergence (MACD)" },
   { value: "obv", label: "On Balance Volume (OBV)" },
   { value: "momentum", label: "Momentum" },
   { value: "priceChannels", label: "Price Channels" },
   { value: "psar", label: "Parabolic SAR (PSAR)" },
   { value: "roc", label: "Rate of Change (ROC)" },
   { value: "rsi", label: "Relative Strength Index (RSI)" },
   { value: "sma", label: "Simple Moving Average (SMA)" },
   { value: "adl", label: "Accumulation Distribution Line (ADL)" },
   { value: "cci", label: "Commodity Channel Index (CCI)" },
   { value: "cmf", label: "Chaikin Money Flow (CMF)" },
   { value: "mfi", label: "Money Flow Index (MFI)" },
   { value: "dmi", label: "Directional Movement Index (DMI)" },
   { value: "cho", label: "Chaikin Oscillator (CHO)" },
   { value: "trix", label: "TRIX" },
   { value: "williamsR", label: "Williams %R" },
   { value: "volumeMa", label: "VolumeMA" },
];